apiVersion: v2
name: profile-hub
description: A Helm chart for Profile Hub application
type: application
version: 0.1.3
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: 16.5.32
    repository: https://charts.bitnami.com/bitnami