apiVersion: v1
kind: Secret
metadata:
  name: {{ include "profile-hub.fullname" . }}-secret
  labels:
    {{- include "profile-hub.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URI: {{ printf "mongodb://%s:%s@%s-mongodb-headless:27017/%s?authSource=admin" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword (include "profile-hub.fullname" .) (index .Values.mongodb.auth.databases 0) | b64enc }}
