apiVersion: v1
kind: Service
metadata:
  name: {{ include "profile-hub.fullname" . }}
  labels:
    {{- include "profile-hub.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "profile-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }} 